site_name: Literature Survey (VPE)
plugins:
  - mkdocstrings:
      paths: ["app", "tests"]  
  - search
theme:
  name: material
  logo: assets/VPE.png
  custom_dir: overrides/
  features:
    - navigation.top
    - navigation.tabs
    # - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  palette:
    # primary: "red"
    # accent: "light-blue"
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: white
      accent: black
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: white
      accent: black
extra_css:
  - custom.css
# use_directory_urls: false
  
repo_url: https://github.com/VirtualPatientEngine/literatureSurvey
repo_name: VPE/LiteratureSurvey

nav:
  - Home: index.md
  # - Neural ODEs: Neural_ODEs.md
  # - Physics-informed GNNs: Physics-informed_GNNs.md
  # - Symbolic regression: Symbolic_regression.md
  # - PINNs: PINNs.md
  # - Latent Space Simulator: Latent_Space_Simulator.md
  # - Koopman Theory: Koopman_Theory.md
  # - API Reference:
  #   - Arxiv: literatureFetch.md
  #   - Tests: test_literatureFetch.md
  