nav:
- Overview: index.md
- Koopman Theory: Koopman_Theory.md
- Latent Space Simulator: Latent_Space_Simulator.md
- PINNs: PINNs.md
- Symbolic regression: Symbolic_regression.md
- Physics-informed GNNs: Physics-informed_GNNs.md
- Neural ODEs: Neural_ODEs.md
plugins:
- mkdocstrings:
    paths:
    - app
    - tests
- search
repo_name: LiteratureSurvey
repo_url: https://github.com/VirtualPatientEngine/literatureSurvey
site_name: Literature Survey (Simulator)
theme:
  custom_dir: overrides/
  features:
  - navigation.top
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - accent: purple
    primary: red
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: lime
    primary: red
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
