extra_css:
- custom.css
nav:
- Symbolic regression: Symbolic regression.md
- Koopman operator theory: Koopman operator theory.md
- PINNs: PINNs.md
- Parametrizing of ODEs using ML: Parametrizing of ODEs using ML.md
- Latent space simulators (VAMP): Latent space simulators (VAMP).md
- Physics-based GNNs: Physics-based GNNs.md
- Neural ODEs: Neural ODEs.md
plugins:
- mkdocstrings:
    paths:
    - app
    - tests
- search
repo_name: VPE/LiteratureSurvey
repo_url: https://github.com/VirtualPatientEngine/literatureSurvey
site_name: Literature Survey (Simulator)
theme:
  custom_dir: overrides/
  features:
  - navigation.top
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - accent: purple
    primary: red
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: lime
    primary: red
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
