extra_css:
- custom.css
nav:
- Home: index.md
- Time-series forecasting: Time-series forecasting.md
- Symbolic regression: Symbolic regression.md
plugins:
- mkdocstrings:
    paths:
    - app
    - tests
- search
repo_name: VPE/LiteratureSurvey
repo_url: https://github.com/VirtualPatientEngine/literatureSurvey
site_name: Literature Survey (VPE)
theme:
  custom_dir: overrides/
  features:
  - navigation.top
  - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  logo: assets/VPE.png
  name: material
  palette:
  - accent: black
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: white
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
