site_name: Literature Survey
plugins:
  - mkdocstrings:
      paths: ["app", "tests"]  
theme:
  name: material
nav:
  - Home: index.md
  - API Reference:
    - Arxiv: literatureFetch.md
    - Tests: test_literatureFetch.md
  